
package _1._0._0._127.cwsdlgeneratordocument.syncservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SyncService", targetNamespace = "http://127.0.0.1/CWSDLGeneratorDocument/syncService.php", wsdlLocation = "http://127.0.0.1/CWSDLGeneratorDocument/syncService.php?wsdl")
public class SyncService
    extends Service
{

    private final static URL SYNCSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(_1._0._0._127.cwsdlgeneratordocument.syncservice.SyncService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = _1._0._0._127.cwsdlgeneratordocument.syncservice.SyncService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1/CWSDLGeneratorDocument/syncService.php?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1/CWSDLGeneratorDocument/syncService.php?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SYNCSERVICE_WSDL_LOCATION = url;
    }

    public SyncService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SyncService() {
        super(SYNCSERVICE_WSDL_LOCATION, new QName("http://127.0.0.1/CWSDLGeneratorDocument/syncService.php", "SyncService"));
    }

    /**
     * 
     * @return
     *     returns SyncPortType
     */
    @WebEndpoint(name = "SyncPort")
    public SyncPortType getSyncPort() {
        return super.getPort(new QName("http://127.0.0.1/CWSDLGeneratorDocument/syncService.php", "SyncPort"), SyncPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SyncPortType
     */
    @WebEndpoint(name = "SyncPort")
    public SyncPortType getSyncPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://127.0.0.1/CWSDLGeneratorDocument/syncService.php", "SyncPort"), SyncPortType.class, features);
    }

}
