
package _1._0._0._127.cwsdlgeneratordocument.syncservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SyncPortType", targetNamespace = "http://127.0.0.1/CWSDLGeneratorDocument/syncService.php")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SyncPortType {


    /**
     * auth doc
     * 
     * @param login
     * @param pass
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://127.0.0.1/CWSDLGeneratorDocument/syncService.php#auth")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "auth", targetNamespace = "http://127.0.0.1/CWSDLGeneratorDocument/syncService.php", className = "_1._0._0._127.cwsdlgeneratordocument.syncservice.Auth")
    @ResponseWrapper(localName = "authResponse", targetNamespace = "http://127.0.0.1/CWSDLGeneratorDocument/syncService.php", className = "_1._0._0._127.cwsdlgeneratordocument.syncservice.AuthResponse")
    public boolean auth(
        @WebParam(name = "login", targetNamespace = "")
        String login,
        @WebParam(name = "pass", targetNamespace = "")
        String pass);

    /**
     * exitAuth doc
     * 
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://127.0.0.1/CWSDLGeneratorDocument/syncService.php#exitAuth")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "exitAuth", targetNamespace = "http://127.0.0.1/CWSDLGeneratorDocument/syncService.php", className = "_1._0._0._127.cwsdlgeneratordocument.syncservice.ExitAuth")
    @ResponseWrapper(localName = "exitAuthResponse", targetNamespace = "http://127.0.0.1/CWSDLGeneratorDocument/syncService.php", className = "_1._0._0._127.cwsdlgeneratordocument.syncservice.ExitAuthResponse")
    public boolean exitAuth();

    /**
     * getHelloWorld doc
     * 
     * @param array2X
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://127.0.0.1/CWSDLGeneratorDocument/syncService.php#getHelloWorld")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHelloWorld", targetNamespace = "http://127.0.0.1/CWSDLGeneratorDocument/syncService.php", className = "_1._0._0._127.cwsdlgeneratordocument.syncservice.GetHelloWorld")
    @ResponseWrapper(localName = "getHelloWorldResponse", targetNamespace = "http://127.0.0.1/CWSDLGeneratorDocument/syncService.php", className = "_1._0._0._127.cwsdlgeneratordocument.syncservice.GetHelloWorldResponse")
    public String getHelloWorld(
        @WebParam(name = "Array2X", targetNamespace = "")
        Array2X array2X);

    /**
     * getHelloWorld2 doc
     * 
     * @param arr
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://127.0.0.1/CWSDLGeneratorDocument/syncService.php#getHelloWorld2")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHelloWorld2", targetNamespace = "http://127.0.0.1/CWSDLGeneratorDocument/syncService.php", className = "_1._0._0._127.cwsdlgeneratordocument.syncservice.GetHelloWorld2")
    @ResponseWrapper(localName = "getHelloWorld2Response", targetNamespace = "http://127.0.0.1/CWSDLGeneratorDocument/syncService.php", className = "_1._0._0._127.cwsdlgeneratordocument.syncservice.GetHelloWorld2Response")
    public String getHelloWorld2(
        @WebParam(name = "arr", targetNamespace = "")
        List<String> arr);

    /**
     * 
     * @param obj2
     * @param obj
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://127.0.0.1/CWSDLGeneratorDocument/syncService.php#getTest")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTest", targetNamespace = "http://127.0.0.1/CWSDLGeneratorDocument/syncService.php", className = "_1._0._0._127.cwsdlgeneratordocument.syncservice.GetTest")
    @ResponseWrapper(localName = "getTestResponse", targetNamespace = "http://127.0.0.1/CWSDLGeneratorDocument/syncService.php", className = "_1._0._0._127.cwsdlgeneratordocument.syncservice.GetTestResponse")
    public String getTest(
        @WebParam(name = "obj", targetNamespace = "")
        String obj,
        @WebParam(name = "obj2", targetNamespace = "")
        String obj2);

}
